- name: Install Nginx package
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create cloud-init directory structure
  file:
    path: "/var/www/html/cloud-init/{{ item.type }}/{{ item.mac_address | replace(':', '-') }}"
    state: directory
    mode: "0755"
  loop: "{{ cloud_init_structure }}"
  loop_control:
    loop_var: item

- name: Create bios meta-data file for {{ item.type }} - {{ item.mac_address }}
  template:
    src: "templates/bios/meta-data.j2"
    dest: "/var/www/html/cloud-init/{{ item.type }}/{{ item.mac_address | replace(':', '-') }}/meta-data"
  loop: "{{ cloud_init_structure }}"
  loop_control:
    loop_var: item
  when: item.type == 'bios'

- name: Create bios user-data file for {{ item.type }} - {{ item.mac_address }}
  template:
    src: "templates/bios/user-data.j2"
    dest: "/var/www/html/cloud-init/{{ item.type }}/{{ item.mac_address | replace(':', '-') }}/user-data"
  loop: "{{ cloud_init_structure }}"
  loop_control:
    loop_var: item
  when: item.type == 'bios'

- name: Create uefi meta-data file for {{ item.type }} - {{ item.mac_address }}
  template:
    src: "templates/uefi/meta-data.j2"
    dest: "/var/www/html/cloud-init/{{ item.type }}/{{ item.mac_address | replace(':', '-') }}/meta-data"
  loop: "{{ cloud_init_structure }}"
  loop_control:
    loop_var: item
  when: item.type == 'uefi'

- name: Create uefi user-data file for {{ item.type }} - {{ item.mac_address }}
  template:
    src: "templates/uefi/user-data.j2"
    dest: "/var/www/html/cloud-init/{{ item.type }}/{{ item.mac_address | replace(':', '-') }}/user-data"
  loop: "{{ cloud_init_structure }}"
  loop_control:
    loop_var: item
  when: item.type == 'uefi'

- name: Change http file permission
  file:
    path: /var/www/html/
    state: directory
    mode: '0755'
    recurse: yes

- name: Copy Nginx configuration file using content
  copy:
    content: |
      server {
          listen 80;
          server_name _;

          root /var/www/html;
          index index.html;

          location / {
              try_files $uri $uri/ =404;
          }

          location /cloud-init/ {
              autoindex on;
          }

          location /iso/ {
              autoindex on;
          }
      }
    dest: /etc/nginx/sites-available/file_server
    mode: '0644'

- name: Enable and restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes