---
#################################################
#
# code : provision.yaml
# function : provision bare metal ocp worker node in DR site (Phase 2)
# author : Leo Chen (weijchen@redhat.com)
# version : 1.1
# update : 2024/09/03
#
#################################################

### task part
- name: DR provision automation playbook
  hosts: pxe-server
  gather_facts: false
  become: true
  become_user: root
  vars:
    ansible_become_password: "P@ssw0rd"
  tasks:
    - name: Install nginx server and setup config
      include_role:
        name: roles/nginx

    - name: Install pxe dhcp dns server and setup config
      include_role:
        name: roles/pxe